# Generated by Django 5.1.3 on 2024-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=200)),
            ],
        ),
    ]
