# Generated by Django 5.1.3 on 2024-11-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackenedapp', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Department',
            new_name='DepartmentId',
        ),
    ]
